command! -nargs=0 BeautySearchCriteria <line1>,<line2>call SearchCriteria#Beauty(<q-args>)
command! -nargs=1 -count=N JoinLinesWithOR call JoinLinesWithOR(<q-args>)
command! -nargs=1 -range=  SplitLineWithOR call SplitLineWithOR(<q-args>)
command! -nargs=1 -range=  SortIPC call SortIPC(<q-args>)
command! -nargs=1 -range=% GetElements call GetElements(<q-args>)
command! -nargs=0 CopyOneline call Copy_oneline()
command! -nargs=0 GenerateSCFromList call GenerateSCFromList()
command! -nargs=0 GenerateListFromSC call GenerateListFromSC()
