command! -nargs=0 BeautySearchCriteria call SearchCriteria#Beauty()
command! -nargs=0 -count JoinLinesWithOR <line1>,<line2>call SearchCriteria#JoinLinesWithOR()
command! -nargs=0 -range  SplitLinesWithOR <line1>,<line2>call SearchCriteria#SplitLineWithOR()
command! -nargs=0 -range  SortIPC <line1>,<line2>call SearchCriteria#SortIPC()
command! -nargs=0 -range=% GetElements <line1>,<line2>call SearchCriteria#GetElements()
command! -nargs=0 CopyOneline call SearchCriteria#Copy_oneline()
command! -nargs=0 GenerateSCFromList call SearchCriteria#GenerateSCFromList()
command! -nargs=0 GenerateListFromSC call SearchCriteria#GenerateListFromSC()
